name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    env:
      CGO_CFLAGS_ALLOW: -Xpreprocessor
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install macos deps
        if: matrix.os == 'macos-11'
        run: |
          brew install vips

      - name: Get dependencies
        run: make get

      - name: Test
        run: make test