name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    env:
      CGO_CFLAGS_ALLOW: -Xpreprocessor
    strategy:
      matrix:
        os: [macos-11]
#        os: [ubuntu-20.04, macos-11]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install linux deps
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo add-apt-repository -y ppa:strukturag/libde265
          sudo add-apt-repository -y ppa:strukturag/libheif
          sudo add-apt-repository -y ppa:tonimelisma/ppa
          sudo apt-get -y install libopenjp2-7
          sudo apt-get -y install libvips-dev

      - name: Install macos deps
        if: matrix.os == 'macos-11'
        run: |
          brew install vips

      - name: Get dependencies
        run: make get

      - name: Test
        run: make test